name: macos-build-ffmpeg5
on: push
jobs:
  macos-build:
    name: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - name: Install ffmpeg and ssl
        run: |
          brew update
          brew install meson ninja cmake sdl2 sdl2_ttf ffmpeg
      - name: Meson build
        env:
          PKG_CONFIG_PATH: "/usr/local/opt/ffmpeg@4/lib/pkgconfig"
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
      - name: Save logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: macos-build-logs
          path: build/meson-logs