name: windows-build
on:
  push:
    branches:
      - '**'

jobs:
  windows-build:
    name: windows-build
    runs-on: windows-2022
    steps:
      - name: Add wix toolset to path
        run: |
          echo "c:\Program Files (x86)\Wix Toolset v3.11\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Restore cached dependencies
        id: cache-dependencies-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            winlibs
          key: windows-build-dependencies
      - name: Download dependencies
        if: steps.cache-dependencies-restore.outputs.cache-hit != 'true'
        run: |
          mkdir winlibs
          curl -L https://github.com/libsdl-org/SDL/releases/download/release-3.2.16/SDL3-devel-3.2.16-VC.zip -o SDL3-devel-3.2.16-VC.zip
          7z x SDL3-devel-3.2.16-VC.zip -owinlibs
          ren winlibs\SDL3-3.2.16 winlibs\SDL3
          curl -L https://github.com/libsdl-org/SDL_ttf/releases/download/release-3.2.2/SDL3_ttf-devel-3.2.2-VC.zip -o SDL3_ttf-devel-3.2.2-VC.zip
          7z x SDL3_ttf-devel-3.2.2-VC.zip -owinlibs
          ren winlibs\SDL3_ttf-3.2.2 winlibs\SDL3_ttf
          curl -L https://github.com/GyanD/codexffmpeg/releases/download/7.0.2/ffmpeg-7.0.2-full_build-shared.7z -o ffmpeg-7.0.2-full_build-shared.7z
          7z x ffmpeg-7.0.2-full_build-shared.7z -owinlibs
          ren winlibs\ffmpeg-7.0.2-full_build-shared winlibs\ffmpeg
      - name: Cache dependencies
        id: cache-dependencies-save
        if: steps.cache-dependencies-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: |
            winlibs
          key: windows-build-dependencies
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Meson build
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          meson-version: 1.8.1
          setup-options: -Dbuildtype=release
